{% set name = "pyflwdir" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: 28a3b04dfc901151d989642aa65432a6c96d7bdecb5e5e530961fab214ee76fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - affine
    - numba >=0.48
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/wflow/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
